---
name: Code Formatter

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  code-formatter:
    name: Code Formatter
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: ministryofjustice/github-actions/code-formatter@1b6396ceb7bf09e741789c4e7eb7b329d5113066 # v15.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
